import sqlite3
import os

project = os.path.dirname(os.path.abspath(__file__))

connection = sqlite3.connect(os.path.join(project, "tasks.db"))  
cursor = connection.cursor()

tasks = (
    ("Kod yaz",),
    ("Ders çalış",),
    ("Kitap oku",),
    ("Spor yap",),
    ("Kahvaltı yap",),
    ("Duş al",),
    ("Odayı temizle",),
    ("Alışveriş yap",),
    ("Film izle",),
    ("Müzik dinle",),
    ("Proje yap",),
    ("Ödev yap",),
    ("Notları düzenle",),
    ("Mail kontrol",),
    ("Toplantıya katıl",),
    ("Rapor yaz",),
    ("Sunum hazırla",),
    ("Dosya düzenle",),
    ("Kod incele",),
    ("Hata düzelt",),
    ("SQL çalış",),
    ("Python çalış",),
    ("C++ çalış",),
    ("JavaScript çalış",),
    ("HTML öğren",),
    ("CSS öğren",),
    ("Flask öğren",),
    ("Git öğren",),
    ("GitHub kullan",),
    ("Veritabanı kur",),
    ("Tablo oluştur",),
    ("Veri ekle",),
    ("Veri sil",),
    ("Veri güncelle",),
    ("Sorgu yaz",),
    ("JOIN çalış",),
    ("API oluştur",),
    ("Backend yaz",),
    ("Frontend yaz",),
    ("Test yap",),
    ("Debug yap",),
    ("Proje başlat",),
    ("Proje bitir",),
    ("Dosya yükle",),
    ("Dosya indir",),
    ("Şifre değiştir",),
    ("Hesap oluştur",),
    ("Giriş yap",),
    ("Çıkış yap",),
    ("Profil düzenle",),
    ("Plan yap",),
    ("Hedef belirle",),
    ("Takvim düzenle",),
    ("Not al",),
    ("Araştırma yap",),
    ("Makale oku",),
    ("Video izle",),
    ("Pratik yap",),
    ("Soru çöz",),
    ("Test çöz",),
    ("Tekrar yap",),
    ("Konu öğren",),
    ("Kod çalıştır",),
    ("Kod kaydet",),
    ("Kod paylaş",),
    ("Repository oluştur",),
    ("Branch aç",),
    ("Commit at",),
    ("Push yap",),
    ("Pull yap",),
    ("Backup al",),
    ("Dosya sil",),
    ("Klasör oluştur",),
    ("Masa düzenle",),
    ("Çamaşır yıka",),
    ("Bulaşık yıka",),
    ("Market alışverişi",),
    ("Fatura öde",),
    ("Evi temizle",),
    ("Çöp at",),
    ("Yürüyüş yap",),
    ("Koşu yap",),
    ("Kahve iç",),
    ("Su iç",),
    ("Dinlen",),
    ("Uyku uyu",),
    ("Erken kalk",),
    ("Alarm kur",),
    ("Telefonu şarj et",),
    ("Bilgisayarı kapat",),
    ("E-postaları sil",),
    ("Fotoğraf düzenle",),
    ("Fotoğraf çek",),
    ("Müzik indir",),
    ("Podcast dinle",),
    ("Yeni fikir bul",),
    ("Hedef kontrol",),
    ("Günü planla",),
    ("Haftayı planla",),
    ("Görevi tamamla",),
)

cursor.executemany("INSERT INTO tasks (title) VALUES (?)", tasks)

connection.commit()
